In [ ]:
# 1
%matplotlib inline
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
import time

In [38]:
# 2
B = np.array([[0,1,1,0,1],[1,0,0,1,0],[0,1,1,0,0]])
S = np.array([[1,2,3,4,5],[2,3,4,5,6],[3,4,5,6,7]])
# n = 3
# t = 5
r = 2
lamb = 0.5
MaxIter = 5
# L = np.random.randn(n,r)

In [39]:
# 将所有的array变为Matrix

# 3 current
def myInverse(B,L,lamb,r,S):
    matrixS = np.matrix(S)
    matrixL = np.matrix(L)
    # B = np.matrix(B)
    n = matrixS.shape[0]
    t = matrixS.shape[1]
    # print('n',n)
    # print('t',t)
    arrayB = np.array(B)
    Y = np.zeros((t,r))
    Y = np.asmatrix(Y)
    # print(Y)
    for i in range(t):
        # print(np.array(B[:,i]))
        # print(B[:,i].T)
        DiagBi = np.diag(arrayB[:,i])
        # print(DiagBi)
        DiagBi = np.asmatrix(DiagBi)
        # print(i,DiagBi.shape)
        # print(i,matrixL.shape)
        Up = matrixL.T * (DiagBi) * (DiagBi) * matrixL + lamb*lamb*np.eye(r)
        Down = (DiagBi * L).T * matrixS[:,i] 
        # Up = np.matrix(Up)
        Yi = Up.I.dot(Down)
        # print(Yi)
        # print(Yi)
        # Y[:,i] = Yi
        # print(Yi)
        Y[i] = Yi.T
        # print(i)
        # print(S)
        # print(matrixS[:,i])
        # print(i,"UP\n",Up)
        # print(i,"Down\n",Down)
        # print(Yi)
    return Y

In [ ]:
# array version
def myInverse(B,L,lamb,r,S):
    Y = np.zeros_like(B)
    Y = np.asmatrix(Y)
    for i in range(B.shape[1]):
        DiagBi = np.diag(B[:,i])
        # print(i,DiagBi)
        matrixS = np.matrix(S)
        Up = L.T.dot(DiagBi.dot(DiagBi).dot(L)) + lamb*lamb*np.eye(r)
        print(type(Up))
        Down = (DiagBi.dot(L)).T.dot(matrixS[:,i])
        Up = np.matrix(Up)
        Yi = Up.I.dot(Down)
        Y[:,i] = Yi
        # print(S)
        # print(matrixS[:,i])
        # print(i,"UP\n",Up)
        # print(i,"Down\n",Down)
        # print(Yi)
    return np.asarray(Y)

In [ ]:
# 将所有的array变为Matrix

# 3.1
def myInverse(B,L,lamb,r,S):
    matrixS = np.matrix(S)
    matrixL = np.matrix(L)
    # B = np.matrix(B)
    n = matrixS.shape[0]
    t = matrixS.shape[1]
    print('n',n)
    print('t',t)
    arrayB = np.array(B)
    Y = np.zeros((r,t))
    Y = np.asmatrix(Y)
    # print(Y)
    for i in range(t):
        # print(np.array(B[:,i]))
        # print(B[:,i].T)
        DiagBi = np.diag(arrayB[:,i])
        # print(DiagBi)
        DiagBi = np.asmatrix(DiagBi)
        # print(i,DiagBi.shape)
        # print(i,matrixL.shape)
        Up = matrixL.T * (DiagBi) * (DiagBi) * matrixL + lamb*lamb*np.eye(r)
        Down = (DiagBi * L).T * matrixS[:,i] 
        # Up = np.matrix(Up)
        Yi = Up.I.dot(Down)
        # print(Yi)
        # print(Yi)
        Y[:,i] = Yi
        # print(Yi)
        # Y[i] = Yi.T
        # print(i)
        # print(S)
        # print(matrixS[:,i])
        # print(i,"UP\n",Up)
        # print(i,"Down\n",Down)
        # print(Yi)
    return np.asarray(Y)

In [ ]:
L = np.random.randn(n,r)

In [ ]:
L

In [ ]:
# L = np.random.randn(n,r)
R = myInverse(B,L,lamb,r,S)
print(R)

In [ ]:
MatrixL = myInverse(B.T,R.T,lamb,r,S.T)
print(MatrixL)

In [178]:
#  4
def ESTI_CS(MatrixS:np.matrix,MatrixB:np.matrix,r:int,lamb:float,MaxIter:int) -> np.matrix:
    '''
    para:

    MatrixS n*t: Sensory Matrix
    MatrixB n*t: Binary index matrix
    r: rank bound
    lamb: tradeoff coefficient
    MaxIter: iteration times: int

    return: 
    MatrixX: estimated environment matrix: np.matrix
    '''
    n = MatrixS.shape[0]
    t = MatrixS.shape[1]
    MatrixL = np.random.randn(n,r)
    MatrixH = np.random.randn(n,n)
    # MatrixT = np.random.randn(t,t)

    MatrixT1 = np.eye(t)
    MatrixT2 = -(np.eye(t-1))
    MatrixT2 = np.pad(MatrixT2,((0,1),(1,0)),mode='constant',constant_values=(0)) 
    MatrixT = MatrixT1+MatrixT2
    # print(MatrixT)


    optimal_L = MatrixL
    optimal_R = 0
    optimal_v = 10000000
    # print(MatrixL)
    for i in range(MaxIter):
        MatrixR = myInverse(MatrixB,MatrixL,lamb,r,MatrixS)
        MatrixL = myInverse(MatrixB.T,MatrixR,lamb,r,MatrixS.T)
        # print(i)
        # print(MatrixR)
        # print(MatrixL.shape)
        # print(MatrixR.shape)
        # Matrix_t1 = MatrixB * ,MatrixL * MatrixR.T
        # print(MatrixB.shape)
        # print(MatrixL*(MatrixR.T))
        Matrix_t1 = np.multiply(MatrixB,MatrixL*MatrixR.T)-S
        Matrix_t2 = MatrixH * MatrixL * MatrixR.T
        # Matrix_t2 = np.multiply(MatrixH,MatrixL)
        Matrix_t3 = MatrixL * MatrixR.T * MatrixT.T


        norm_t1 = np.square(np.linalg.norm(Matrix_t1,'f'))
        # print('round',round(norm_t1))
        # print('round2',round(norm_t12))
        norm_t2 = np.square(np.linalg.norm(Matrix_t2,'f'))
        norm_t3 = np.square(np.linalg.norm(Matrix_t3,'f'))
        norm_l = np.square(np.linalg.norm(MatrixL,'f'))
        norm_r = np.square(np.linalg.norm(MatrixR.T,'f'))

        sum_v = norm_t1+lamb*(norm_l+norm_r)+norm_t2+norm_t3

        if sum_v < optimal_v:
            optimal_L = MatrixL
            optimal_R = MatrixR
            optimal_v = sum_v

    return optimal_L*optimal_R.T


In [179]:
# 5
Matrix_X = ESTI_CS(S*B,B,r,lamb,5)
print(abs((Matrix_X-S)).sum())
print(Matrix_X)

2
<class 'int'>
0.5
<class 'float'>
47.13584880462017
[[-2.33576863  2.00995422  3.00072759 -5.83942157  4.91582275]
 [ 1.98290554 -0.74078482 -1.33076706  4.95726386 -3.5380725 ]
 [-0.79888229  3.8487406   5.00979987 -1.99720573  3.76080273]]


<class 'numpy.matrix'>


In [156]:
S

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [ ]:
B

In [155]:
S*B

array([[0, 2, 3, 0, 5],
       [2, 0, 0, 5, 0],
       [0, 4, 5, 0, 0]])

In [ ]:
Matrix_X

In [43]:
# 6
abs((Matrix_X-S)).sum()

21.95464952267686

In [ ]:
t = 7
MatrixT1 = np.eye(t)
MatrixT2 = -(np.eye(t-1))
pp = np.pad(MatrixT2,((0,1),(1,0)),mode='constant',constant_values=(0))
print(MatrixT1)
print(MatrixT2)
print(pp+MatrixT1)

# 计算矩阵F范数平方的方法速度对比

In [ ]:
# A = np.array([[-4,-3,-2,-1],[-1,0,1,0],[2,3,4,1]])
A = np.random.randn(10,5)
A = np.mat(A)

In [ ]:
result = []
summ = 0
for i in range(100):
    A = np.random.randn(i,i)
    A = np.mat(A)
    t1 = time.time()
    f1 = np.square(np.linalg.norm(A,'f'))
    t2 = time.time()
    f2 = np.trace(A.H*A)
    t3 = time.time()
    period1 = t2-t1
    period2 = t3-t2
    result.append((i,period2-period1))
    if period2 > period1:
        summ += 1

### 可以看到 使用np.linalg.norm 再平方，要比用矩阵的迹要快

In [ ]:
summ