In [1]:
# 1
%matplotlib inline
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
a = np.array([1,2,3,4,5,6])

In [ ]:
r = 10
n = 30
t = 20

In [ ]:
Ir = np.eye(r)

In [ ]:
L = np.random.randn(n,r)

In [ ]:
L.shape

In [109]:
# 2
# B = np.array([[0,1,1,0,1],[1,0,0,1,0],[0,1,1,0,0]])
# S = np.array([[1,2,3,4,5],[2,3,4,5,6],[3,4,5,6,7]])
# n = 3
# t = 5
r = 2
lamb = 0.5
MaxIter = 5
# L = np.random.randn(n,r)

In [ ]:
B[:,1]

In [ ]:
matrixB = np.matrix(B)

In [ ]:
Bi = matrixB[:,3]

In [ ]:
DiagB = np.diag(B[:,1])
print(B[:,1])
print(DiagB)

In [43]:

def myInverse(B,L,lamb,r,S):
    Y = np.zeros_like(B)
    Y = np.asmatrix(Y)
    for i in range(B.shape[1]):
        DiagBi = np.diag(B[:,i])
        # print(i,DiagBi)
        matrixS = np.matrix(S)
        Up = L.T.dot(DiagBi.dot(DiagBi).dot(L)) + lamb*lamb*np.eye(r)
        print(type(Up))
        Down = (DiagBi.dot(L)).T.dot(matrixS[:,i])
        Up = np.matrix(Up)
        Yi = Up.I.dot(Down)
        Y[:,i] = Yi
        # print(S)
        # print(matrixS[:,i])
        # print(i,"UP\n",Up)
        # print(i,"Down\n",Down)
        # print(Yi)
    return np.asarray(Y)

In [162]:
# 将所有的array变为Matrix

# 3
def myInverse(B,L,lamb,r,S):
    matrixS = np.matrix(S)
    matrixL = np.matrix(L)
    # B = np.matrix(B)
    n = matrixS.shape[0]
    t = matrixS.shape[1]
    # print('n',n)
    # print('t',t)
    arrayB = np.array(B)
    Y = np.zeros((t,r))
    Y = np.asmatrix(Y)
    # print(Y)
    for i in range(t):
        # print(np.array(B[:,i]))
        # print(B[:,i].T)
        DiagBi = np.diag(arrayB[:,i])
        # print(DiagBi)
        DiagBi = np.asmatrix(DiagBi)
        # print(i,DiagBi.shape)
        # print(i,matrixL.shape)
        Up = matrixL.T * (DiagBi) * (DiagBi) * matrixL + lamb*lamb*np.eye(r)
        Down = (DiagBi * L).T * matrixS[:,i] 
        # Up = np.matrix(Up)
        Yi = Up.I.dot(Down)
        # print(Yi)
        # print(Yi)
        # Y[:,i] = Yi
        # print(Yi)
        Y[i] = Yi.T
        # print(i)
        # print(S)
        # print(matrixS[:,i])
        # print(i,"UP\n",Up)
        # print(i,"Down\n",Down)
        # print(Yi)
    return Y

In [146]:
# 将所有的array变为Matrix

# 3.1
def myInverse(B,L,lamb,r,S):
    matrixS = np.matrix(S)
    matrixL = np.matrix(L)
    # B = np.matrix(B)
    n = matrixS.shape[0]
    t = matrixS.shape[1]
    print('n',n)
    print('t',t)
    arrayB = np.array(B)
    Y = np.zeros((r,t))
    Y = np.asmatrix(Y)
    # print(Y)
    for i in range(t):
        # print(np.array(B[:,i]))
        # print(B[:,i].T)
        DiagBi = np.diag(arrayB[:,i])
        # print(DiagBi)
        DiagBi = np.asmatrix(DiagBi)
        # print(i,DiagBi.shape)
        # print(i,matrixL.shape)
        Up = matrixL.T * (DiagBi) * (DiagBi) * matrixL + lamb*lamb*np.eye(r)
        Down = (DiagBi * L).T * matrixS[:,i] 
        # Up = np.matrix(Up)
        Yi = Up.I.dot(Down)
        # print(Yi)
        # print(Yi)
        Y[:,i] = Yi
        # print(Yi)
        # Y[i] = Yi.T
        # print(i)
        # print(S)
        # print(matrixS[:,i])
        # print(i,"UP\n",Up)
        # print(i,"Down\n",Down)
        # print(Yi)
    return np.asarray(Y)

In [136]:
L = np.random.randn(n,r)

In [143]:
L

array([[ 1.38212559, -2.35127517],
       [-1.05680175, -0.21411883],
       [-0.32515165, -1.24068142]])

In [141]:
# 4
# L = np.random.randn(n,r)
R = myInverse(B,L,lamb,r,S)
print(R)

n 3
t 5
0 (3, 3)
0 (3, 2)
1 (3, 3)
1 (3, 2)
2 (3, 3)
2 (3, 2)
3 (3, 3)
3 (3, 2)
4 (3, 3)
4 (3, 2)
[[-1.49616917 -1.98105853 -2.27458948 -3.74042292  0.89879545]
 [-0.30313916 -2.09135104 -2.69637669 -0.75784791 -1.52903284]]


In [148]:
MatrixL = myInverse(B.T,R.T,lamb,r,S.T)
print(MatrixL)

n 5
t 3
0 (5, 5)
0 (5, 2)
1 (5, 5)
1 (5, 2)
2 (5, 5)
2 (5, 2)
[[ 1.34385199 -1.26531376 -0.89740536]
 [-2.23999383 -0.2563655  -1.06147026]]


In [68]:
print(B)

[[0 1 1 0 1]
 [1 0 0 1 0]
 [0 1 1 0 0]]


In [208]:
def ESTI_CS(MatrixS,MatrixB,r,lamb,MaxIter):
    '''
    para:

    MatrixS n*t: Sensory Matrix
    MatrixB n*t: Binary index matrix
    r: rank bound
    lamb: tradeoff coefficient
    MaxIter: iteration times

    return: 
    MatrixX: estimated environment matrix
    '''
    n = MatrixS.shape[0]
    t = MatrixS.shape[1]
    MatrixL = np.random.randn(n,r)
    MatrixH = np.random.randn(n,n)
    MatrixT = np.random.randn(t,t)
    # print(MatrixL)
    for i in range(MaxIter):
        MatrixR = myInverse(MatrixB,MatrixL,lamb,r,MatrixS)
        MatrixL = myInverse(MatrixB.T,MatrixR,lamb,r,MatrixS.T)
        # print(i)
        # print(MatrixR)
        # print(MatrixL.shape)
        # print(MatrixR.shape)
        # Matrix_t1 = MatrixB * ,MatrixL * MatrixR.T
        # print(MatrixB.shape)
        # print(MatrixL*(MatrixR.T))
        Matrix_t1 = np.multiply(MatrixB,MatrixL*MatrixR.T)
        Matrix_t2 = MatrixH * MatrixL * MatrixR.T
        # Matrix_t2 = np.multiply(MatrixH,MatrixL)
        Matrix_t3 = MatrixL * MatrixR.T * MatrixT.T
    return MatrixL*MatrixR.T


In [209]:
Matrix_X = ESTI_CS(S,B,r,lamb,MaxIter)

In [202]:
S

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [203]:
B

array([[0, 1, 1, 0, 1],
       [1, 0, 0, 1, 0],
       [0, 1, 1, 0, 0]])

In [204]:
S*B

array([[0, 2, 3, 0, 5],
       [2, 0, 0, 5, 0],
       [0, 4, 5, 0, 0]])

In [211]:
Matrix_X

matrix([[0.60938026, 2.01515958, 2.99486968, 1.52345064, 4.84061117],
        [1.94905074, 3.43886729, 4.17056727, 4.87262684, 1.60506623],
        [2.00927047, 3.88729843, 4.9149701 , 5.02317617, 3.23410088]])

In [212]:
Matrix_X-S

matrix([[-0.39061974,  0.01515958, -0.00513032, -2.47654936, -0.15938883],
        [-0.05094926,  0.43886729,  0.17056727, -0.12737316, -4.39493377],
        [-0.99072953, -0.11270157, -0.0850299 , -0.97682383, -3.76589912]])

In [ ]:
PP = np.array([[2,1]])
print(PP.T)

In [ ]:
lam*lam*np.eye(r)

In [ ]:
A = np.array([[-4,-3,-2],[-1,0,1],[2,3,4]])
A = np.mat(A)

In [ ]:
S.shape[0]

In [ ]:
np.trace(A.H * A)