In [1]:
# 1
%matplotlib inline
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [295]:
import time

In [109]:
# 2
# B = np.array([[0,1,1,0,1],[1,0,0,1,0],[0,1,1,0,0]])
# S = np.array([[1,2,3,4,5],[2,3,4,5,6],[3,4,5,6,7]])
# n = 3
# t = 5
r = 2
lamb = 0.5
MaxIter = 5
# L = np.random.randn(n,r)

In [43]:
# array version
def myInverse(B,L,lamb,r,S):
    Y = np.zeros_like(B)
    Y = np.asmatrix(Y)
    for i in range(B.shape[1]):
        DiagBi = np.diag(B[:,i])
        # print(i,DiagBi)
        matrixS = np.matrix(S)
        Up = L.T.dot(DiagBi.dot(DiagBi).dot(L)) + lamb*lamb*np.eye(r)
        print(type(Up))
        Down = (DiagBi.dot(L)).T.dot(matrixS[:,i])
        Up = np.matrix(Up)
        Yi = Up.I.dot(Down)
        Y[:,i] = Yi
        # print(S)
        # print(matrixS[:,i])
        # print(i,"UP\n",Up)
        # print(i,"Down\n",Down)
        # print(Yi)
    return np.asarray(Y)

In [162]:
# 将所有的array变为Matrix

# 3
def myInverse(B,L,lamb,r,S):
    matrixS = np.matrix(S)
    matrixL = np.matrix(L)
    # B = np.matrix(B)
    n = matrixS.shape[0]
    t = matrixS.shape[1]
    # print('n',n)
    # print('t',t)
    arrayB = np.array(B)
    Y = np.zeros((t,r))
    Y = np.asmatrix(Y)
    # print(Y)
    for i in range(t):
        # print(np.array(B[:,i]))
        # print(B[:,i].T)
        DiagBi = np.diag(arrayB[:,i])
        # print(DiagBi)
        DiagBi = np.asmatrix(DiagBi)
        # print(i,DiagBi.shape)
        # print(i,matrixL.shape)
        Up = matrixL.T * (DiagBi) * (DiagBi) * matrixL + lamb*lamb*np.eye(r)
        Down = (DiagBi * L).T * matrixS[:,i] 
        # Up = np.matrix(Up)
        Yi = Up.I.dot(Down)
        # print(Yi)
        # print(Yi)
        # Y[:,i] = Yi
        # print(Yi)
        Y[i] = Yi.T
        # print(i)
        # print(S)
        # print(matrixS[:,i])
        # print(i,"UP\n",Up)
        # print(i,"Down\n",Down)
        # print(Yi)
    return Y

In [146]:
# 将所有的array变为Matrix

# 3.1
def myInverse(B,L,lamb,r,S):
    matrixS = np.matrix(S)
    matrixL = np.matrix(L)
    # B = np.matrix(B)
    n = matrixS.shape[0]
    t = matrixS.shape[1]
    print('n',n)
    print('t',t)
    arrayB = np.array(B)
    Y = np.zeros((r,t))
    Y = np.asmatrix(Y)
    # print(Y)
    for i in range(t):
        # print(np.array(B[:,i]))
        # print(B[:,i].T)
        DiagBi = np.diag(arrayB[:,i])
        # print(DiagBi)
        DiagBi = np.asmatrix(DiagBi)
        # print(i,DiagBi.shape)
        # print(i,matrixL.shape)
        Up = matrixL.T * (DiagBi) * (DiagBi) * matrixL + lamb*lamb*np.eye(r)
        Down = (DiagBi * L).T * matrixS[:,i] 
        # Up = np.matrix(Up)
        Yi = Up.I.dot(Down)
        # print(Yi)
        # print(Yi)
        Y[:,i] = Yi
        # print(Yi)
        # Y[i] = Yi.T
        # print(i)
        # print(S)
        # print(matrixS[:,i])
        # print(i,"UP\n",Up)
        # print(i,"Down\n",Down)
        # print(Yi)
    return np.asarray(Y)

In [136]:
L = np.random.randn(n,r)

In [143]:
L

array([[ 1.38212559, -2.35127517],
       [-1.05680175, -0.21411883],
       [-0.32515165, -1.24068142]])

In [141]:
# L = np.random.randn(n,r)
R = myInverse(B,L,lamb,r,S)
print(R)

n 3
t 5
0 (3, 3)
0 (3, 2)
1 (3, 3)
1 (3, 2)
2 (3, 3)
2 (3, 2)
3 (3, 3)
3 (3, 2)
4 (3, 3)
4 (3, 2)
[[-1.49616917 -1.98105853 -2.27458948 -3.74042292  0.89879545]
 [-0.30313916 -2.09135104 -2.69637669 -0.75784791 -1.52903284]]


In [148]:
MatrixL = myInverse(B.T,R.T,lamb,r,S.T)
print(MatrixL)

n 5
t 3
0 (5, 5)
0 (5, 2)
1 (5, 5)
1 (5, 2)
2 (5, 5)
2 (5, 2)
[[ 1.34385199 -1.26531376 -0.89740536]
 [-2.23999383 -0.2563655  -1.06147026]]


In [68]:
print(B)

[[0 1 1 0 1]
 [1 0 0 1 0]
 [0 1 1 0 0]]


In [500]:
#  4
def ESTI_CS(MatrixS,MatrixB,r,lamb,MaxIter):
    '''
    para:

    MatrixS n*t: Sensory Matrix
    MatrixB n*t: Binary index matrix
    r: rank bound
    lamb: tradeoff coefficient
    MaxIter: iteration times

    return: 
    MatrixX: estimated environment matrix
    '''
    n = MatrixS.shape[0]
    t = MatrixS.shape[1]
    MatrixL = np.random.randn(n,r)
    MatrixH = np.random.randn(n,n)
    MatrixT = np.random.randn(t,t)

    optimal_L = MatrixL
    optimal_R = 0
    optimal_v = 10000000
    # print(MatrixL)
    for i in range(MaxIter):
        MatrixR = myInverse(MatrixB,MatrixL,lamb,r,MatrixS)
        MatrixL = myInverse(MatrixB.T,MatrixR,lamb,r,MatrixS.T)
        # print(i)
        # print(MatrixR)
        # print(MatrixL.shape)
        # print(MatrixR.shape)
        # Matrix_t1 = MatrixB * ,MatrixL * MatrixR.T
        # print(MatrixB.shape)
        # print(MatrixL*(MatrixR.T))
        Matrix_t1 = np.multiply(MatrixB,MatrixL*MatrixR.T)-S
        Matrix_t2 = MatrixH * MatrixL * MatrixR.T
        # Matrix_t2 = np.multiply(MatrixH,MatrixL)
        Matrix_t3 = MatrixL * MatrixR.T * MatrixT.T


        norm_t1 = np.square(np.linalg.norm(Matrix_t1,'f'))
        # print('round',round(norm_t1))
        # print('round2',round(norm_t12))
        norm_t2 = np.square(np.linalg.norm(Matrix_t2,'f'))
        norm_t3 = np.square(np.linalg.norm(Matrix_t3,'f'))
        norm_l = np.square(np.linalg.norm(MatrixL,'f'))
        norm_r = np.square(np.linalg.norm(MatrixR.T,'f'))

        sum_v = norm_t1+lamb*(norm_l+norm_r)+norm_t2+norm_t3

        if sum_v < optimal_v:
            optimal_L = MatrixL
            optimal_R = MatrixR
            optimal_v = sum_v

    return optimal_L*optimal_R.T


In [530]:
# 5
Matrix_X = ESTI_CS(S*B,B,r,lamb,MaxIter)

In [202]:
S

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [203]:
B

array([[0, 1, 1, 0, 1],
       [1, 0, 0, 1, 0],
       [0, 1, 1, 0, 0]])

In [204]:
S*B

array([[0, 2, 3, 0, 5],
       [2, 0, 0, 5, 0],
       [0, 4, 5, 0, 0]])

In [522]:
Matrix_X

matrix([[0.44922936, 2.0136595 , 2.98901686, 1.1230734 , 4.76986203],
        [1.91589544, 1.7376297 , 2.23047889, 4.7897386 , 1.1869346 ],
        [0.55430107, 3.90918513, 4.91921603, 1.38575266, 1.84108663]])

In [531]:
# 6
abs((Matrix_X-S)).sum()

37.1569524781507

# 计算矩阵F范数平方的方法速度对比

In [441]:
# A = np.array([[-4,-3,-2,-1],[-1,0,1,0],[2,3,4,1]])
A = np.random.randn(10,5)
A = np.mat(A)

In [489]:
result = []
summ = 0
for i in range(100):
    A = np.random.randn(i,i)
    A = np.mat(A)
    t1 = time.time()
    f1 = np.square(np.linalg.norm(A,'f'))
    t2 = time.time()
    f2 = np.trace(A.H*A)
    t3 = time.time()
    period1 = t2-t1
    period2 = t3-t2
    result.append((i,period2-period1))
    if period2 > period1:
        summ += 1

### 可以看到 使用np.linalg.norm 再平方，要比用矩阵的迹要快

In [496]:
summ

98