In [1]:
%matplotlib inline
import numpy as np
import pandas as pd
import os,sys
import utils
import matplotlib.pyplot as plt
from consts import sensor_lat as lat
from consts import sensor_log as log
from consts import valid_sensor_res_10 as valid_sensor_list
from consts import sensor_day_seconds as day_seconds
from consts import sensor_week_seconds as week_seconds 
from consts import sensor_start_time_unix as start_time
from consts import sensor_end_time_unix as end_time
from consts import sensor_epoch_length as epoch_length
import consts
from numpy import array
import time

In [ ]:
print(consts.sensor_start_time_unix)

In [3]:
df = pd.read_hdf('optimal.h5','df')

In [2]:
start_time = 1172678400
df = pd.read_hdf('data.h5','df_sub')

In [6]:
unix_column = 'Time since the epoch [s]'
idd = 'Station ID'

In [6]:
df.shape

(994276, 12)

In [25]:
start_time = 1174492800

In [7]:
df.columns

Index(['Station ID', 'Year', 'Month', 'Day', 'Hour', 'Minute', 'Second',
       'Time since the epoch [s]', 'Sequence Number', 'Ambient Temperature',
       'Surface Temperature', 'Relative Humidity [%]'],
      dtype='object')

In [27]:
time_stamps = np.arange(start_time,start_time+week_seconds+epoch_length,epoch_length)

In [8]:
start_time = 1174406400
time_stamps = np.arange(start_time,start_time+week_seconds+epoch_length,epoch_length)
coverage_test(df,time_stamps,valid_sensor_list)
# 3-21

[82]
[82]
[82]
[71 82]
[71 82]
[19 71 82]
[19 71 82]
[19 71 82]
[19 71 82]
[19 71 82]
[19 71 82]
[19 71 82]
[19 71 82]
[19 71 82]
[19 71 82]
[19 71 82]
[19 71 82]
[19 71 82]
[19 71 82]
[19 71 82]
[19 71 82]
[19 71 82]
[19 71 82]
[19 71 82]
[19 71 82]
[19 71 82]
[19 71 82]
[19 71 82]
[19 71 82]
[19 71 82]
[19 71 82]
[71 82]
[71 82]
[71 82]
[71 82]
[71 82]
[71 82]
[71 82]
[71 82]
[71 82]
[71 82]
[71 82]
[71 82]
[71 82]
[71 82]
[71 82]
[71 82]
[71 82]
[71 82]
[71 82]
[71 82]
[71 82]
[71 82]
[71 82]
[71 82]
[59 71 82 98]
[71 82 98]
[71 82 98]
[71 82 98]
[71 82 98]
[71 82 98]
[71 82 98]
[71 82 98]
[71 82 98]
[71 82 98]
[71 82 98]
[71 82 98]
[71 82 98]
[71 82 98]
[71 82 98]
[71 82 98]
[71 82 98]
[71 82 98]
[71 82 98]
[71 82 98]
[71 82 98]
[71 82 98]
[71 82 98]
[71 82 98]
[71 82 98]
[71 82 98]
[71 82 98]
[71 82 98]
[71 82 98]
[71 82 98]
[71 82 98]
[71 82 98]
[71 82 98]
[71 82 98]
[71 82]
[71 82]
[71 82]
[71 82]
[71 82]
[71 82]
[71 82]
[71 82]
[71 82]
[71 82]
[71 82]
[71 82]
[71 82]
[71 82]
[7

1073

In [8]:
start_time = 1174492800
time_stamps = np.arange(start_time,start_time+week_seconds+epoch_length,epoch_length)
coverage_test(df,time_stamps,valid_sensor_list)
# 3-22

[71]
[71]
[71]
[71]
[71]
[71]
[71]
[59 71 98]
[71 98]
[71 98]
[71 98]
[71 98]
[71 98]
[71 98]
[71 98]
[71 98]
[71 98]
[71 98]
[71 98]
[71 98]
[71 98]
[71 98]
[71 98]
[71 98]
[71 98]
[71 98]
[71 98]
[71 98]
[71 98]
[71 98]
[71 98]
[71 98]
[71 98]
[71 98]
[71 98]
[71 98]
[71 98]
[71 98]
[71 98]
[71 98]
[71 98]
[71]
[71]
[71]
[71]
[71]
[71]
[71]
[71]
[71]
[71]
[71]
[71]
[71]
[71]
[71]
[71]
[71]
[71]
[71]
[71]
[71]
[71]
[71]
[71]
[71]
[71]
[71]
[71]
[71]
[71]
[71]
[71]
[71 73]
[71 73]
[71 73]
[71 73]
[71 73]
[71 73]
[71 73]
[71 73]
[71 73]
[71 73]
[71]
[71]
[71]
[71]
[71]
[71]
[71]
[14 71]
[14 71]
[14 71]
[14 71]
[14 71]
[14 71]
[14 71]
[14 71]
[14 71]
[14 71]
[14 71]
[14 71]
[14 71]
[14 71]
[14 71]
[14 71]
[14 71]
[14 71]
[14 71]
[14 71]
[14 71]
[14 71]
[14 71]
[14 71]
[14 71]
[14 71]
[14 71]
[14 71]
[14 71]
[14 71]
[14 71]
[14 71]
[14 71 98]
[14 71 98]
[14 71 98]
[14 71 98]
[14 71 98]
[14 71 98]
[14 71 98]
[14 71 98]
[14 71 98]
[14 71 98]
[14 71 98]
[14 71 98]
[14 71 98]
[14 71 98]
[14 7

729

In [7]:
start_time = 1172678400
time_stamps = np.arange(start_time,start_time+week_seconds+epoch_length,epoch_length)
coverage_test(df,time_stamps,valid_sensor_list)
# 3-1

[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[59]
[59]
[59]
[59]
[59]
[59]
[59]
[59]
[59]
[59]
[59]
[59]
[59]
[59]
[59]
[59]
[59]
[59]
[59]
[59]
[59]
[59]
[59]
[59]
[59]
[59]
[59]
[59]
[59]
[59]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[81]
[81]
[]
[]
[]
[79]
[]
[79]
[]
[]
[]
[79]
[]
[79]
[79]
[79]
[79]
[79]
[79]
[79]
[79]
[79]
[79]
[79]
[]
[79]
[79]
[79]
[79]
[79]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[59]
[59]
[59]
[59]
[59]
[59]
[59]
[59]
[59]
[59]
[59]
[59]
[59]
[59]
[59]
[59]
[59]
[59]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[

91

In [9]:
end_time = start_time+week_seconds

In [10]:
optimal_df = df[(df[unix_column] > start_time) & (df[unix_column] < end_time)]

In [11]:
print(optimal_df.shape)

(991342, 12)


In [12]:
optimal_df.to_hdf('optimal.h5',key='optimal_df',mode='a')

In [7]:
print(len(valid_sensor_list))

44


In [8]:
print(len(consts.valid_sensor_res_10_old))

51


In [ ]:
start_time = 1172678400
time_stamps = np.arange(start_time,start_time+week_seconds+epoch_length,epoch_length)
coverage_test(df,time_stamps,valid_sensor_list)
# 3-1

In [8]:
df.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
Int64Index: 994276 entries, 3042 to 926905
Data columns (total 12 columns):
 #   Column                    Non-Null Count   Dtype  
---  ------                    --------------   -----  
 0   Station ID                994276 non-null  int64  
 1   Year                      994276 non-null  int64  
 2   Month                     994276 non-null  int64  
 3   Day                       994276 non-null  int64  
 4   Hour                      994276 non-null  int64  
 5   Minute                    994276 non-null  int64  
 6   Second                    994276 non-null  int64  
 7   Time since the epoch [s]  994276 non-null  int64  
 8   Sequence Number           994276 non-null  int64  
 9   Ambient Temperature       970015 non-null  float64
 10  Surface Temperature       973443 non-null  float64
 11  Relative Humidity [%]     970695 non-null  float64
dtypes: float64(3), int64(9)
memory usage: 98.6 MB


In [4]:
def coverage_test(df,time_stamps,valid_sensor_list):
    error = 0
    diff_list = []
    # all_np_list = []
    sub_df_num  = 0
    for i in range(len(time_stamps)-1):
        # print(i)
        # print(time_stamps[i],time_stamps[i+1])
        sub_df = df[(df[unix_column] > time_stamps[i]) & (df[unix_column] < time_stamps[i+1])]
        sensor_list = sub_df[idd].values
        uniq = np.unique(sensor_list)
        diff = np.setdiff1d(valid_sensor_list,uniq)    
        # np_court = all_np(sensor_list)
        # all_np_list.append(np_court)
        error += len(diff)
        diff_list.append(len(diff))
        print(diff)
        sub_df_num += len(sub_df)
    print(sub_df_num/error)
    diff_list = np.array(diff_list)
    print("var: {0} \t std: {1} ".format(diff_list.var(),diff_list.std()))
    return error