In [2]:
from numpy import array
from scipy.linalg import svd

A = array([[1,2],[3,4],[5,6]])

In [3]:
print(A)

[[1 2]
 [3 4]
 [5 6]]


In [4]:
U,s,vt = svd(A)

In [5]:
print(U)
print(s)
print(vt)

[[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]
[9.52551809 0.51430058]
[[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]


In [16]:
# Reconstruct SVD
from numpy import array
from numpy import diag
from numpy import dot
from numpy import zeros
from scipy.linalg import svd
# define a matrix
A = array([[1, 2], [3, 4], [5, 6]])
print(A)
# Singular-value decomposition
U, s, VT = svd(A)
# create m x n Sigma matrix
Sigma = zeros((A.shape[0], A.shape[1]))
# populate Sigma with n x n diagonal matrix
print(Sigma)
print(s)

[[1 2]
 [3 4]
 [5 6]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[9.52551809 0.51430058]


In [29]:
tmp = diag([s[0],0])
print(tmp)

[[9.52551809 0.        ]
 [0.         0.        ]]


In [11]:
Sigma[:A.shape[1],:A.shape[1]]

array([[0., 0.],
       [0., 0.]])

In [30]:
Sigma[:A.shape[1],:A.shape[1]] = tmp
print(Sigma)

[[9.52551809 0.        ]
 [0.         0.        ]
 [0.         0.        ]]


In [31]:
# Sigma[:A.shape[1], :A.shape[1]] = diag(s)
# reconstruct matrix
B = U.dot(Sigma.dot(VT))
print(B)

[[1.35662819 1.71846235]
 [3.09719707 3.92326845]
 [4.83776596 6.12807454]]


In [46]:
A = array([[1,2,3],[4,5,6],[7,8,9]])
b = diag([1,2,3])

In [47]:
print(A)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [49]:
bm = zeros((3,5))
bm[:3,:3] = b

In [53]:
print(bm)

[[1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]]


In [55]:
c = array([[1,2,3,4,5],[2,4,6,8,10],[3,6,9,12,15],[4,8,12,16,20],[5,10,15,20,25]])

In [56]:
print(c)

[[ 1  2  3  4  5]
 [ 2  4  6  8 10]
 [ 3  6  9 12 15]
 [ 4  8 12 16 20]
 [ 5 10 15 20 25]]


In [68]:
cp = array([c[0],c[1],c[2],zeros(5),zeros(5)])
print(cp)

[[ 1.  2.  3.  4.  5.]
 [ 2.  4.  6.  8. 10.]
 [ 3.  6.  9. 12. 15.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]


In [61]:
tmp = A.dot(bm)
print(tmp)

[[ 1.  4.  9.  0.  0.]
 [ 4. 10. 18.  0.  0.]
 [ 7. 16. 27.  0.  0.]]


In [70]:
dp = tmp.dot(cp)
print(dp)

[[ 36.  72. 108. 144. 180.]
 [ 78. 156. 234. 312. 390.]
 [120. 240. 360. 480. 600.]]


In [59]:
d = A.dot(bm).dot(c)
print(d)

[[ 36.  72. 108. 144. 180.]
 [ 78. 156. 234. 312. 390.]
 [120. 240. 360. 480. 600.]]


In [94]:
a = array([[1,2,3,4,5]])
b = array([[5,6,7,8,9]])
c = a.T.dot(b)
print(c)

[[ 5  6  7  8  9]
 [10 12 14 16 18]
 [15 18 21 24 27]
 [20 24 28 32 36]
 [25 30 35 40 45]]
