In [5]:
from numpy import *
import numpy as np

In [14]:
def load_data(spatial_size, temporal_size, miss_ratio=0):
    origin = np.random.randint(1,5,size=(spatial_size,temporal_size))
    mask = np.ones_like(origin)
    k = round(spatial_size*temporal_size*miss_ratio)
    ri = np.random.choice(spatial_size*temporal_size,k,replace=False)
    mask.flat[ri] = 0
    return origin,mask

origin,mask = load_data(4,5,0.2)

In [15]:
print(origin)

[[4 4 1 1 3]
 [2 1 2 4 2]
 [3 1 1 4 4]
 [1 4 4 2 3]]


In [16]:
print(mask)

[[1 1 1 0 1]
 [1 0 1 0 0]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [17]:
print(origin * mask)

[[4 4 1 0 3]
 [2 0 2 0 0]
 [3 1 1 4 4]
 [1 4 4 2 3]]


In [43]:

from numpy import * 

def load_data1(file_path):
    f = open(file_path)
    V = []
    for line in f.readlines():
        lines = line.strip().split("\t")
        data = []
        for x in lines:
            data.append(float(x))
        V.append(data)
    return mat(V)



def train(V,mask, r, k, e):
    m, n = shape(origin)
    W = mat(random.random((m, r)))
    H = mat(random.random((r, n)))

    for x in arange(k):
        #error 
        V_pre = W * H
        # print(V_pre.shape)
        # print(multiply(V_pre,mask))
        E = V - multiply(V_pre,mask)
        err = np.sum(abs(E))
        #print E
        # err = 0.0
        # for i in arange(m):
        #     for j in arange(n):
        #         err += E[i,j] * E[i,j]
        print(err)

        if err < e:
            break

        a = W.T * V
        b = W.T * W * H
        #c = V * H.T
        #d = W * H * H.T
        for i_1 in np.arange(r):
            for j_1 in arange(n):
                if b[i_1,j_1] != 
                    H[i_1,j_1] = H[i_1,j_1] * a[i_1,j_1] / b[i_1,j_1]

        c = V * H.T
        d = W * H * H.T
        for i_2 in arange(m):
            for j_2 in arange(r):
                if d[i_2, j_2] != 0:
                    W[i_2,j_2] = W[i_2,j_2] * c[i_2,j_2] / d[i_2, j_2]

    return W,H 


if __name__ == "__main__":
    
    

    # V = load_data(file_path)
    origin,mask = load_data(4,5,0.5)
    W, H = train(origin*mask,mask, 2, 100, 1e-5 )

    print(origin*mask)
    # print(W)
    # print(H)
    print(origin)
    print(W*H)
    print(W*H-origin)
    print(np.sum(abs(W * H-origin)))

21.85260969801695
9.243749269437957
5.78815668182018
4.98774389050004
4.560371226935063
4.3001824439581995
4.086072814560584
4.002388043785919
4.0214928867266
4.055179564388306
4.08436302463296
4.106393772272927
4.121618671717078
4.1336633273100665
4.143984047181353
4.150969520804778
4.155702903175448
4.158932628707495
4.16116258144042
4.162725875105278
4.163839673812101
4.164644196733944
4.16522990320173
4.165656039332528
4.165962779921364
4.1661786588922745
4.166324778654145
4.166417104314974
4.166467802162053
4.166486159688731
4.16647929958535
4.166452740742617
4.166410819405005
4.166356990012314
4.166294034254572
4.166224206770613
4.166149339747763
4.166070921354779
4.165990157093742
4.165908019331879
4.165825288062636
4.1657425847621665
4.165660400596071
4.165579119909425
4.165499039748431
4.165420386040228
4.165343326965041
4.165267983977974
4.165194440870897
4.165122751206165
4.165052944402228
4.164985030706484
4.164919005251941
4.164854851361459
4.164792543235413
4.164732048135