In [1]:
import utility
import pandas as pd
import numpy as np

In [2]:
from consts import sensor_unix_column as unix_column
from consts import sensor_idd as idd
from consts import sensor_a_temperature as a_temperature

In [3]:
a_tmp,_,_,index,time_stamp = utility.get_h5_data()

In [ ]:
time_stamp.shape

In [15]:
index

array([    2,     9,    11, ..., 19376, 19380, 19381])

In [4]:
df_list = utility.dataset_read('df_list')

In [ ]:
rb_df_list = utility.dataset_read('rb_optimal')

In [5]:
res = utility.remove_duplicated(df_list[index[0]])

In [6]:
window = 3

In [7]:
len(df_list)

20160

In [18]:
zeros = np.zeros(len(df_list))
zeros[index] = 1
def compute_temporal_sub_count(window):
    sum = 0
    for i in range(len(zeros)-window+1):
        sub = zeros[i:i+window]
        if 0 not in sub:
            print(i)
            sum += 1
        if sum > 10:
            break
    return sum

In [25]:
compute_temporal_sub_count(2)

25
31
34
45
57
110
111
112
113
126
127


11

In [10]:
compute_temporal_sub_count(3)

110
111
112
126
134
140
141
167
181
182
183


11

In [11]:
abs(df_list[140].dropna()[a_temperature].values - df_list[141].dropna()[a_temperature].values)

array([0.07, 0.14, 0.02, 0.06, 0.  , 0.09, 0.01, 0.05, 0.08, 0.19, 0.01,
       0.02, 0.2 , 0.  , 0.08, 0.06, 0.02, 0.02, 0.01, 0.18, 0.02, 0.  ,
       0.01, 0.02, 0.02, 0.1 , 0.06, 0.1 , 0.07, 0.08, 0.26, 0.01, 0.18,
       0.04, 0.13, 0.01, 0.08, 0.12, 0.11, 0.2 , 0.06, 0.04, 0.03, 0.04,
       0.05, 0.01, 0.  , 0.02])

In [81]:
time_stamp[110]

1172706900

In [77]:
time_stamp[111]

1172706930

In [12]:
compute_temporal_sub_count(4)

110
111
140
181
182
194
195
196
197
213
225


11

In [ ]:
compute_temporal_sub_count(5)

In [ ]:
compute_temporal_sub_count(6)

In [ ]:
compute_temporal_sub_count(7)

In [ ]:
compute_temporal_sub_count(8)

In [16]:
sum = 0
for i,item in enumerate(index):
    if i < len(index)-3:
        if index[i+1] == index[i]+1 and index[i+2] == index[i+1]+1:
            sum += 1

In [17]:
sum

2838

In [13]:
len(index)

5959

In [14]:
index

array([    2,     9,    11, ..., 19376, 19380, 19381])

In [ ]:
len(df_list[index[0]])

In [5]:
df = pd.read_hdf('data.h5','df_sub')
df_nona = df.dropna()

In [23]:
idds = df_nona[idd]

In [24]:
idds_uniq = idds.unique()

In [25]:
idds_uniq

array([  7,   8,  11,  14,  17,  19,  23,  26,  27,  31,  33,  34,  35,
        40,  46,  47,  49,  51,  55,  57,  59,  60,  61,  62,  63,  65,
        69,  70,  71,  72,  73,  75,  76,  79,  80,  81,  82,  84,  87,
        88,  89,  93,  96,  97,  98, 100, 103, 104, 109, 111, 121])

In [30]:
idd_dict = {}

In [31]:
# init
for i in idds_uniq:
    idd_dict[i] = 0

In [34]:
for i in idds:
    idd_dict[i] += 1

In [44]:
sorted(idd_dict.items(),key=lambda kv:(kv[1],kv[0]),reverse=True)

[(121, 1257313),
 (26, 520877),
 (34, 515512),
 (8, 505421),
 (23, 503635),
 (46, 501266),
 (17, 482219),
 (100, 481359),
 (14, 478876),
 (70, 474867),
 (96, 473786),
 (11, 472048),
 (93, 471177),
 (31, 465717),
 (60, 462032),
 (87, 461762),
 (72, 459969),
 (97, 455899),
 (51, 455363),
 (104, 455286),
 (73, 455119),
 (35, 454316),
 (19, 453966),
 (103, 453364),
 (84, 447767),
 (49, 446618),
 (80, 435758),
 (33, 428389),
 (76, 426899),
 (40, 426519),
 (89, 421637),
 (79, 419798),
 (81, 388595),
 (111, 371313),
 (75, 369027),
 (88, 365499),
 (65, 362265),
 (98, 336712),
 (62, 322947),
 (59, 273292),
 (61, 265435),
 (69, 264172),
 (57, 257244),
 (63, 253729),
 (71, 252737),
 (109, 240136),
 (82, 194276),
 (55, 156833),
 (47, 132198),
 (7, 128827),
 (27, 87038)]

In [32]:
import pickle
input_file = open('../sub_index_array.pkl','rb')
sub_index_array = pickle.load(input_file)
input_file.close()

In [40]:
len(sub_index_array[0][1])

346050

335675